"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

type Cliente = { cli_id: number; cli_nombre?: string | null; cli_apellido?: string | null; cli_mail?: string | null; cli_celu?: string | null; cli_tel1?: string | null };
const name = (client: Cliente) => `${client.cli_apellido?.trim() ?? ""}, ${client.cli_nombre?.trim() ?? ""}`.replace(/^, /, "") || `Cliente #${client.cli_id}`;

export function ComunicacionPanel({ initialClient = null }: { initialClient?: Cliente | null }) {
  const router = useRouter(); const [error, setError] = useState(""); const [query, setQuery] = useState(initialClient ? name(initialClient) : ""); const [matches, setMatches] = useState<Cliente[]>([]); const [selected, setSelected] = useState<Cliente | null>(initialClient); const [searching, setSearching] = useState(false);
  async function search() { setError(""); if (query.trim().length < 2) return setError("Escribí al menos 2 caracteres para buscar."); setSearching(true); const response = await fetch(`/api/clientes?q=${encodeURIComponent(query)}`); setSearching(false); if (!response.ok) return setError((await response.json()).error ?? "No se pudo buscar"); setMatches(await response.json()); }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); if (!selected) return setError("Elegí un cliente antes de enviar."); const body = Object.fromEntries(new FormData(event.currentTarget)); const response = await fetch("/api/comunicaciones", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...body, cliente_id: selected.cli_id }) }); if (!response.ok) return setError((await response.json()).error ?? "No se pudo enviar el email"); event.currentTarget.reset(); setSelected(null); setQuery(""); setMatches([]); router.replace("/dashboard/comunicaciones"); }
  return <form onSubmit={submit} className="max-w-2xl space-y-3 rounded-xl border bg-white p-4"><div><label className="mb-1 block text-xs font-medium text-slate-500">Cliente</label><div className="flex gap-2"><Input value={query} onChange={(event) => { setQuery(event.target.value); setSelected(null); }} placeholder="Nombre, apellido, teléfono o email"/><Button type="button" variant="outline" onClick={search} disabled={searching}>{searching ? "…" : "Buscar"}</Button></div>{selected && <div className="mt-2 flex items-center justify-between gap-2 rounded-lg bg-blue-50 px-3 py-2 text-sm text-blue-900"><span className="min-w-0 truncate">{name(selected)} · {selected.cli_mail || "sin email"}</span><button type="button" className="text-xs font-medium" onClick={() => setSelected(null)}>Cambiar</button></div>}{!selected && matches.length > 0 && <div className="mt-2 max-h-48 overflow-y-auto rounded-lg border">{matches.map((client) => <button key={client.cli_id} type="button" onClick={() => { setSelected(client); setMatches([]); setQuery(name(client)); }} className="block w-full border-b px-3 py-2 text-left text-sm hover:bg-slate-50 last:border-0"><b>{name(client)}</b><span className="ml-2 text-xs text-slate-500">{client.cli_mail || client.cli_celu || client.cli_tel1 || "sin contacto"}</span></button>)}</div>}</div><Input name="asunto" placeholder="Asunto" required/><textarea name="mensaje" placeholder="Mensaje" required rows={6} className="w-full rounded-lg border border-input p-2.5 text-sm"/><Button type="submit" disabled={!selected}>Enviar email y registrar</Button>{error && <p className="text-sm text-red-600">{error}</p>}</form>;
}
