"use client";

import { useRouter } from "next/navigation";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

type Producto = { id: number; nombre: string; categoria: string; stock: number; stock_minimo: number; precio: number | string; proveedor?: string | null; vencimiento?: string | null; codigo_barras?: string | null };

function ProductForm({ producto, onSubmit }: { producto?: Producto; onSubmit: (data: Record<string, FormDataEntryValue>) => void }) {
  return <form onSubmit={(event) => { event.preventDefault(); onSubmit(Object.fromEntries(new FormData(event.currentTarget))); }} className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">
    <Input name="nombre" defaultValue={producto?.nombre} placeholder="Producto" required/><Input name="categoria" defaultValue={producto?.categoria} placeholder="Categoría" required/><Input name="stock" type="number" min="0" defaultValue={producto?.stock ?? 0} required/><Input name="stock_minimo" type="number" min="0" defaultValue={producto?.stock_minimo ?? 0} required/><Input name="precio" type="number" min="0" step="0.01" defaultValue={producto?.precio ?? 0} required/><Input name="proveedor" defaultValue={producto?.proveedor ?? ""} placeholder="Proveedor"/><Input name="vencimiento" type="date" defaultValue={producto?.vencimiento ?? ""}/><Input name="codigo_barras" defaultValue={producto?.codigo_barras ?? ""} placeholder="Código de barras"/><Button type="submit">{producto ? "Guardar cambios" : "Agregar producto"}</Button>
  </form>;
}

function EditProduct({ producto, onSave, onDelete }: { producto: Producto; onSave: (data: Record<string, FormDataEntryValue>, id: number) => void; onDelete: (id: number) => void }) {
  return <details className="mt-3"><summary className="cursor-pointer text-xs font-medium text-blue-700">Editar producto</summary><div className="mt-2 rounded-lg border bg-slate-50 p-3"><ProductForm producto={producto} onSubmit={(data) => onSave(data, producto.id)}/><Button className="mt-2" size="xs" variant="destructive" type="button" onClick={() => onDelete(producto.id)}>Eliminar producto</Button></div></details>;
}

export function InventarioPanel({ productos }: { productos: Producto[] }) {
  const router = useRouter(); const [error, setError] = useState(""); const [search, setSearch] = useState(""); const [lowOnly, setLowOnly] = useState(false);
  const save = async (data: Record<string, FormDataEntryValue>, id?: number) => { setError(""); const response = await fetch(id ? `/api/inventario/${id}` : "/api/inventario", { method: id ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(data) }); if (!response.ok) return setError((await response.json()).error ?? "No se pudo guardar"); router.refresh(); };
  const remove = async (id: number) => { if (!confirm("¿Eliminar este producto? Las ventas existentes no se eliminan.")) return; const response = await fetch(`/api/inventario/${id}`, { method: "DELETE" }); if (!response.ok) return setError((await response.json()).error ?? "No se pudo eliminar"); router.refresh(); };
  const low = productos.filter((product) => product.stock <= product.stock_minimo).length;
  const visible = productos.filter((product) => (!lowOnly || product.stock <= product.stock_minimo) && `${product.nombre} ${product.categoria} ${product.proveedor ?? ""} ${product.codigo_barras ?? ""}`.toLowerCase().includes(search.toLowerCase().trim()));
  const price = (product: Producto) => `$${Number(product.precio).toLocaleString("es-AR", { minimumFractionDigits: 2 })}`;

  return <div className="space-y-5"><div className="rounded-xl border bg-amber-50 p-3 text-sm text-amber-800">{low ? `⚠️ ${low} producto${low === 1 ? "" : "s"} con stock bajo.` : "✓ No hay productos bajo el stock mínimo."}</div><details className="rounded-xl border bg-white p-4"><summary className="cursor-pointer font-medium text-slate-700">+ Agregar producto</summary><ProductForm onSubmit={save}/></details><div className="flex flex-wrap gap-2"><Input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Buscar producto, proveedor, categoría o código…" className="max-w-md text-sm"/><Button type="button" variant={lowOnly ? "default" : "outline"} size="sm" onClick={() => setLowOnly(!lowOnly)}>⚠️ {lowOnly ? "Mostrar todo" : "Sólo stock bajo"}</Button></div>
    <div className="space-y-2 md:hidden">{visible.map((product) => <article key={product.id} className={`rounded-xl border bg-white p-4 shadow-sm ${product.stock <= product.stock_minimo ? "border-amber-300 bg-amber-50/40" : ""}`}><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate font-semibold text-slate-800">{product.nombre}</p><p className="mt-1 truncate text-sm text-slate-500">{product.categoria}{product.proveedor ? ` · ${product.proveedor}` : ""}</p></div><span className={`shrink-0 rounded-full px-2 py-1 text-xs ${product.stock <= product.stock_minimo ? "bg-amber-100 font-medium text-amber-800" : "bg-slate-100 text-slate-600"}`}>Stock {product.stock}</span></div><div className="mt-3 grid grid-cols-2 gap-2 text-xs text-slate-500"><span>Mínimo: {product.stock_minimo}</span><span>Precio: {price(product)}</span><span>Vence: {product.vencimiento || "—"}</span><span className="truncate">Código: {product.codigo_barras || "—"}</span></div><EditProduct producto={product} onSave={save} onDelete={remove}/></article>)}{!visible.length && <p className="rounded-xl border bg-white p-8 text-center text-slate-400">Sin productos para este filtro.</p>}</div>
    <div className="hidden overflow-x-auto rounded-xl border bg-white md:block"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-slate-600"><tr><th className="p-3">Producto</th><th>Stock</th><th>Mínimo</th><th>Precio</th><th>Vencimiento</th><th/></tr></thead><tbody>{visible.map((product) => <tr key={product.id} className={`border-t ${product.stock <= product.stock_minimo ? "bg-amber-50/50" : ""}`}><td className="p-3"><b>{product.nombre}</b><span className="block text-xs text-slate-500">{product.categoria}{product.proveedor ? ` · ${product.proveedor}` : ""}</span></td><td className={product.stock <= product.stock_minimo ? "font-semibold text-amber-700" : ""}>{product.stock}</td><td>{product.stock_minimo}</td><td>{price(product)}</td><td>{product.vencimiento || "—"}</td><td className="p-2"><EditProduct producto={product} onSave={save} onDelete={remove}/></td></tr>)}</tbody></table>{!visible.length && <p className="p-8 text-center text-slate-400">Sin productos para este filtro.</p>}</div>{error && <p className="text-sm text-red-600">{error}</p>}</div>;
}
