"use client";

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

type Producto = { id: number; nombre: string; stock: number; precio: number | string };
type Item = { producto_id: number; cantidad: number };

export function VentasPanel({ productos }: { productos: Producto[] }) {
  const router = useRouter(); const [items, setItems] = useState<Item[]>([]); const [productId, setProductId] = useState(""); const [quantity, setQuantity] = useState(1); const [notas, setNotas] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const enriched = useMemo(() => items.map((item) => ({ ...item, producto: productos.find((product) => product.id === item.producto_id)! })).filter((item) => item.producto), [items, productos]);
  const money = (amount: number) => `$${amount.toLocaleString("es-AR", { minimumFractionDigits: 2 })}`;
  const total = enriched.reduce((sum, item) => sum + Number(item.producto.precio) * item.cantidad, 0);
  function add() { setError(""); const id = Number(productId); const product = productos.find((item) => item.id === id); if (!product || quantity < 1) return; const existing = items.find((item) => item.producto_id === id); const current = existing?.cantidad ?? 0; if (current + quantity > product.stock) return setError(`Stock insuficiente para ${product.nombre}`); setItems(existing ? items.map((item) => item.producto_id === id ? { ...item, cantidad: item.cantidad + quantity } : item) : [...items, { producto_id: id, cantidad: quantity }]); setProductId(""); setQuantity(1); }
  function remove(id: number) { setItems(items.filter((item) => item.producto_id !== id)); }
  async function submit() { setError(""); if (!items.length) return setError("Agregá al menos un producto"); setBusy(true); const response = await fetch("/api/ventas", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ items, notas }) }); setBusy(false); if (!response.ok) return setError((await response.json()).error ?? "No se pudo registrar la venta"); setItems([]); setNotas(""); router.refresh(); }
  return <div className="space-y-3 rounded-xl border bg-white p-4"><div className="grid gap-2 sm:grid-cols-[1fr_110px_auto]"><select value={productId} onChange={(event) => setProductId(event.target.value)} className="h-9 min-w-0 rounded-lg border px-2 text-sm"><option value="">Elegí un producto</option>{productos.filter((product) => product.stock > 0).map((product) => <option key={product.id} value={product.id}>{product.nombre} · stock {product.stock} · {money(Number(product.precio))}</option>)}</select><Input value={quantity} onChange={(event) => setQuantity(Number(event.target.value))} type="number" min="1"/><Button type="button" onClick={add}>Agregar</Button></div>
    {enriched.length > 0 && <><div className="space-y-2 md:hidden">{enriched.map((item) => <article key={item.producto_id} className="rounded-lg border p-3"><div className="flex items-start justify-between gap-3"><div><p className="font-medium text-slate-800">{item.producto.nombre}</p><p className="mt-1 text-xs text-slate-500">{item.cantidad} × {money(Number(item.producto.precio))}</p></div><div className="text-right"><p className="font-medium text-slate-800">{money(Number(item.producto.precio) * item.cantidad)}</p><Button className="mt-2" type="button" size="xs" variant="destructive" onClick={() => remove(item.producto_id)}>Quitar</Button></div></div></article>)}</div><div className="hidden overflow-x-auto md:block"><table className="w-full text-sm"><thead className="border-b text-left text-slate-500"><tr><th className="p-2">Producto</th><th className="p-2">Cant.</th><th className="p-2">Precio</th><th className="p-2">Subtotal</th><th/></tr></thead><tbody>{enriched.map((item) => <tr key={item.producto_id} className="border-b"><td className="p-2 font-medium">{item.producto.nombre}</td><td className="p-2">{item.cantidad}</td><td className="p-2">{money(Number(item.producto.precio))}</td><td className="p-2">{money(Number(item.producto.precio) * item.cantidad)}</td><td className="p-2"><Button type="button" size="xs" variant="destructive" onClick={() => remove(item.producto_id)}>Quitar</Button></td></tr>)}</tbody></table></div></>}
    <div className="grid gap-2 sm:grid-cols-[1fr_auto] sm:items-center"><Input value={notas} onChange={(event) => setNotas(event.target.value)} placeholder="Notas (opcional)"/><div className="text-right"><div className="text-sm text-slate-500">Total</div><div className="text-xl font-bold text-slate-800">{money(total)}</div></div></div><Button type="button" onClick={submit} disabled={busy || !items.length}>{busy ? "Registrando…" : "Confirmar venta"}</Button>{error && <p className="text-sm text-red-600">{error}</p>}</div>;
}
