"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

export function NuevaConsulta({ pacienteId }: { pacienteId: number }) {
  const router = useRouter(); const [open,setOpen]=useState(false); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
  const submit = async (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); setError(""); setBusy(true); const form=e.currentTarget; const data=new FormData(form); const file=data.get("archivo"); let adjuntos: unknown[]=[]; if(file instanceof File && file.size){ const upload=new FormData(); upload.set("paciente_id",String(pacienteId)); upload.set("archivo",file); const r=await fetch("/api/archivos",{method:"POST",body:upload}); if(!r.ok){setBusy(false);return setError((await r.json()).error??"No se pudo subir el archivo");} adjuntos=[await r.json()]; } const b=Object.fromEntries(data); const r=await fetch("/api/consultas",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...b,paciente_id:pacienteId,adjuntos})}); setBusy(false); if(!r.ok)return setError((await r.json()).error??"No se pudo guardar");form.reset();setOpen(false);router.refresh(); };
  return <div className="mb-3">{!open?<Button size="sm" onClick={()=>setOpen(true)}>+ Nueva consulta</Button>:<form onSubmit={submit} className="grid gap-2 rounded-xl border bg-white p-4 sm:grid-cols-2"><Input name="fecha" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/><Input name="titulo" placeholder="Motivo / título" required/><Input name="peso" type="number" step="0.01" placeholder="Peso (kg)"/><Input name="temperatura" type="number" step="0.1" placeholder="Temperatura °C"/><Input name="profesional" placeholder="Profesional"/><Input name="archivo" type="file" accept="image/*,application/pdf" className="text-sm"/><textarea name="detalle" placeholder="Detalle clínico" required className="min-h-24 rounded-lg border p-2 text-sm sm:col-span-2"/><textarea name="tratamiento" placeholder="Tratamiento / indicaciones" className="min-h-20 rounded-lg border p-2 text-sm sm:col-span-2"/><div className="flex gap-2"><Button type="submit" disabled={busy}>{busy?"Guardando…":"Guardar consulta"}</Button><Button type="button" variant="outline" onClick={()=>setOpen(false)}>Cancelar</Button></div><p className="text-xs text-slate-500">Adjuntá una imagen o PDF de hasta 8 MB. El archivo queda privado.</p>{error&&<p className="text-sm text-red-600 sm:col-span-2">{error}</p>}</form>}</div>;
}
