import Link from "next/link";
import { createAdminClient } from "@/lib/supabase/admin";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

export default async function BuscarPage({ searchParams }: { searchParams: Promise<{ q?: string }> }) {
  const { q = "" } = await searchParams; const term = q.trim(); const safeTerm = term.replace(/[,%()]/g, " "); const numericId = /^\d+$/.test(term) ? Number(term) : null; const supabase = createAdminClient();
  const [clientes, pacientes] = term ? await Promise.all([
    supabase.from("clientes").select("cli_id,cli_nombre,cli_apellido,cli_celu,cli_tel1,cli_mail").or(`${numericId !== null ? `cli_id.eq.${numericId},` : ""}cli_nombre.ilike.%${safeTerm}%,cli_apellido.ilike.%${safeTerm}%,cli_celu.ilike.%${safeTerm}%,cli_tel1.ilike.%${safeTerm}%,cli_mail.ilike.%${safeTerm}%`).limit(20),
    supabase.from("pacientes").select("pac_id,pac_nombre,pac_apellido,pac_raz_nombre,pac_cliente,pac_microchip").or(`${numericId !== null ? `pac_id.eq.${numericId},pac_cliente.eq.${numericId},` : ""}pac_nombre.ilike.%${safeTerm}%,pac_apellido.ilike.%${safeTerm}%,pac_microchip.ilike.%${safeTerm}%`).limit(20),
  ]) : [{data:[]},{data:[]}];
  return <div className="mx-auto max-w-4xl"><h1 className="text-2xl font-semibold text-slate-800">🔎 Buscador global</h1><p className="mb-5 text-sm text-slate-500">Buscá por dueño, mascota, teléfono, email, microchip o ID.</p><form className="flex gap-2" method="GET"><Input name="q" defaultValue={term} placeholder="Ej.: Samantha, 11 4448…, microchip…" autoFocus/><Button type="submit">Buscar</Button></form>{term && <div className="mt-6 grid gap-5 md:grid-cols-2"><section><h2 className="mb-3 text-base font-semibold text-slate-700">👥 Clientes ({clientes.data?.length ?? 0})</h2><div className="space-y-2">{clientes.data?.map(c=><Link key={c.cli_id} href={`/dashboard/clientes/${c.cli_id}`} className="block rounded-xl border bg-white p-4 shadow-sm hover:border-slate-400"><div className="font-medium text-slate-800">{c.cli_apellido?.trim()}, {c.cli_nombre?.trim()}</div><div className="mt-1 text-xs text-slate-500">{c.cli_celu?.trim() || c.cli_tel1?.trim() || c.cli_mail?.trim() || "Sin contacto"}</div></Link>)}{!clientes.data?.length&&<p className="rounded-xl border bg-white p-4 text-sm text-slate-400">Sin clientes.</p>}</div></section><section><h2 className="mb-3 text-base font-semibold text-slate-700">🐾 Pacientes ({pacientes.data?.length ?? 0})</h2><div className="space-y-2">{pacientes.data?.map(p=><Link key={p.pac_id} href={`/dashboard/pacientes/${p.pac_id}`} className="block rounded-xl border bg-white p-4 shadow-sm hover:border-slate-400"><div className="font-medium text-slate-800">{p.pac_nombre?.trim()} {p.pac_apellido?.trim()}</div><div className="mt-1 text-xs text-slate-500">{p.pac_raz_nombre?.trim() || "Sin raza"} · Dueño #{p.pac_cliente}{p.pac_microchip?.trim() ? ` · Chip: ${p.pac_microchip.trim()}` : ""}</div></Link>)}{!pacientes.data?.length&&<p className="rounded-xl border bg-white p-4 text-sm text-slate-400">Sin mascotas.</p>}</div></section></div>}</div>;
}
