"use client";

import { FormEvent, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { argentinaDate } from "@/lib/date";

type Cliente = { cli_id: number; cli_nombre?: string | null; cli_apellido?: string | null; cli_mail?: string | null; cli_celu?: string | null; cli_tel1?: string | null };
type Paciente = { pac_id: number; pac_nombre?: string | null; pac_cliente?: number; pac_raz_nombre?: string | null };
type Turno = { id: number; fecha: string; hora: string; cliente_id: number; paciente_id: number; motivo: string; estado: string };
const iso = (date: Date) => argentinaDate(date);
const clean = (value: unknown) => String(value ?? "").trim();
const ownerName = (client: Cliente) => `${clean(client.cli_apellido)}, ${clean(client.cli_nombre)}`.replace(/^, /, "") || `Cliente #${client.cli_id}`;
function monday(value: string) { const date = new Date(`${value}T12:00:00`); date.setDate(date.getDate() - ((date.getDay() + 6) % 7)); return iso(date); }
function days(start: string) { return Array.from({ length: 7 }, (_, index) => { const date = new Date(`${start}T12:00:00`); date.setDate(date.getDate() + index); return iso(date); }); }
function shift(start: string, amount: number) { const date = new Date(`${start}T12:00:00`); date.setDate(date.getDate() + amount); return iso(date); }
function label(date: string) { return new Intl.DateTimeFormat("es-AR", { weekday: "short", day: "numeric", month: "short" }).format(new Date(`${date}T12:00:00`)); }

export function TurnosPanel({ turnos, clientes, pacientes, today, initialWeek, initialClient = null, initialPets = [], initialPatientId }: { turnos: Turno[]; clientes: Cliente[]; pacientes: Paciente[]; today: string; initialWeek: string; initialClient?: Cliente | null; initialPets?: Paciente[]; initialPatientId?: number }) {
  const router = useRouter(); const [error, setError] = useState(""); const [week, setWeek] = useState(initialWeek); const [query, setQuery] = useState(initialClient ? ownerName(initialClient) : ""); const [matches, setMatches] = useState<Cliente[]>([]); const [selectedClient, setSelectedClient] = useState<Cliente | null>(initialClient); const [selectedPatient, setSelectedPatient] = useState(initialPatientId ? String(initialPatientId) : ""); const [appointmentPets, setAppointmentPets] = useState<Paciente[]>(initialPets); const [searching, setSearching] = useState(false);
  const weekDays = useMemo(() => days(week), [week]);
  const owner = (id: number) => { const client = clientes.find((item) => item.cli_id === id); return client ? ownerName(client) : `Cliente #${id}`; };
  const pet = (id: number) => clean(pacientes.find((item) => item.pac_id === id)?.pac_nombre) || `Mascota #${id}`;
  async function searchClients() { setError(""); if (query.trim().length < 2) return setError("Escribí al menos 2 caracteres para buscar al dueño."); setSearching(true); const response = await fetch(`/api/clientes?q=${encodeURIComponent(query)}`); setSearching(false); if (!response.ok) return setError((await response.json()).error ?? "No se pudo buscar"); setMatches(await response.json()); }
  async function pickClient(client: Cliente) { setSelectedClient(client); setSelectedPatient(""); setMatches([]); setQuery(ownerName(client)); const response = await fetch(`/api/pacientes?cliente_id=${client.cli_id}`); if (!response.ok) return setError((await response.json()).error ?? "No se pudieron cargar las mascotas"); setAppointmentPets(await response.json()); }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); if (!selectedClient || !selectedPatient) return setError("Elegí dueño y mascota antes de guardar."); const response = await fetch("/api/turnos", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(Object.fromEntries(new FormData(event.currentTarget))) }); if (!response.ok) return setError((await response.json()).error ?? "No se pudo guardar"); event.currentTarget.reset(); setSelectedClient(null); setSelectedPatient(""); setAppointmentPets([]); setQuery(""); router.refresh(); }
  async function change(id: number, estado: string) { const response = await fetch(`/api/turnos/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ estado }) }); if (!response.ok) setError((await response.json()).error ?? "No se pudo actualizar"); router.refresh(); }
  function goToWeek(next: string) { setWeek(next); router.push(`/dashboard/turnos?week=${next}`); }

  return <div className="space-y-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-xl font-semibold text-slate-800">Turnos</h1><p className="text-sm text-slate-500">Agenda semanal compartida.</p></div><div className="flex flex-wrap items-center gap-2"><Button variant="outline" size="sm" onClick={() => goToWeek(shift(week, -7))}>← Semana</Button><Input type="date" value={week} onChange={(event) => goToWeek(monday(event.target.value))} className="w-auto"/><Button variant="outline" size="sm" onClick={() => goToWeek(monday(today))}>Hoy</Button><Button variant="outline" size="sm" onClick={() => goToWeek(shift(week, 7))}>Semana →</Button></div></div>
    <form onSubmit={submit} className="grid min-w-0 gap-2 rounded-xl border bg-white p-4 sm:grid-cols-2 lg:grid-cols-4"><Input name="fecha" type="date" defaultValue={today} required/><Input name="hora" type="time" required/><div className="relative flex gap-2 sm:col-span-2"><Input value={query} onChange={(event) => { setQuery(event.target.value); setSelectedClient(null); setSelectedPatient(""); }} placeholder="Buscar dueño"/><Button type="button" variant="outline" onClick={searchClients} disabled={searching}>{searching ? "…" : "Buscar"}</Button>{matches.length > 0 && <div className="absolute left-0 right-0 top-10 z-20 max-h-48 overflow-y-auto rounded-lg border bg-white shadow-lg">{matches.map((client) => <button key={client.cli_id} type="button" className="block w-full border-b px-3 py-2 text-left text-sm hover:bg-slate-50 last:border-0" onClick={() => pickClient(client)}><b>{ownerName(client)}</b><span className="ml-2 text-xs text-slate-500">{client.cli_celu || client.cli_tel1 || client.cli_mail || ""}</span></button>)}</div>}</div><input type="hidden" name="cliente_id" value={selectedClient?.cli_id || ""}/><select name="paciente_id" value={selectedPatient} onChange={(event) => setSelectedPatient(event.target.value)} disabled={!selectedClient} required className="h-9 min-w-0 rounded-lg border px-2 text-sm disabled:bg-slate-100"><option value="">{selectedClient ? "Elegí mascota" : "Primero elegí dueño"}</option>{appointmentPets.map((patient) => <option key={patient.pac_id} value={patient.pac_id}>{clean(patient.pac_nombre)}{patient.pac_raz_nombre ? ` · ${patient.pac_raz_nombre}` : ""}</option>)}</select><Input name="motivo" placeholder="Motivo" required/><Input name="notas" placeholder="Notas (opcional)"/><Button type="submit">Agregar turno</Button>{error && <p className="text-sm text-red-600 sm:col-span-2 lg:col-span-4">{error}</p>}</form>
    <div className="overflow-x-auto rounded-xl border bg-slate-100 p-2 [-webkit-overflow-scrolling:touch]"><div className="grid min-w-[760px] grid-cols-7 gap-2">{weekDays.map((day) => { const dayTurns = turnos.filter((turn) => turn.fecha === day); return <div key={day} className="min-h-72 rounded-lg bg-white p-2"><div className={`mb-2 border-b pb-2 text-center text-xs font-semibold ${day === today ? "text-blue-700" : "text-slate-600"}`}>{label(day)}</div><div className="space-y-2">{dayTurns.map((turn) => <div key={turn.id} className={`rounded-md border p-2 text-xs ${turn.estado === "cancelado" ? "bg-slate-50 opacity-60" : turn.estado === "atendido" ? "border-green-200 bg-green-50" : "bg-white"}`}><div className="font-semibold text-slate-800">{String(turn.hora).slice(0, 5)} · {pet(turn.paciente_id)}</div><div className="mt-1 text-slate-600">{owner(turn.cliente_id)}</div><div className="mt-1 text-slate-500">{turn.motivo}</div><select value={turn.estado} onChange={(event) => change(turn.id, event.target.value)} className="mt-2 w-full rounded border bg-white px-1 py-1 text-[11px]"><option>pendiente</option><option>confirmado</option><option>atendido</option><option>cancelado</option></select></div>)}{!dayTurns.length && <p className="py-4 text-center text-xs text-slate-300">Sin turnos</p>}</div></div>; })}</div></div>
  </div>;
}
