-- Módulos migrados del sistema Node legado: inventario, ventas y comunicaciones.
-- Ejecutar una vez desde el SQL Editor de Supabase, antes de desplegar esta versión.

create table if not exists public.inventario (
  id bigint generated by default as identity primary key,
  nombre text not null check (length(trim(nombre)) > 0),
  categoria text not null check (length(trim(categoria)) > 0),
  stock integer not null default 0 check (stock >= 0),
  stock_minimo integer not null default 0 check (stock_minimo >= 0),
  precio numeric(12, 2) not null default 0 check (precio >= 0),
  vencimiento date,
  proveedor text,
  codigo_barras text unique,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

create table if not exists public.ventas (
  id bigint generated by default as identity primary key,
  fecha timestamptz not null default now(),
  veterinario_nombre text not null,
  importe_total numeric(12, 2) not null default 0 check (importe_total >= 0),
  cantidad_items integer not null default 0 check (cantidad_items >= 0),
  notas text,
  creado_en timestamptz not null default now()
);

create table if not exists public.venta_items (
  id bigint generated by default as identity primary key,
  venta_id bigint not null references public.ventas(id) on delete cascade,
  producto_id bigint not null references public.inventario(id),
  producto_nombre text not null,
  cantidad integer not null check (cantidad > 0),
  precio_unitario numeric(12, 2) not null check (precio_unitario >= 0),
  importe_total numeric(12, 2) not null check (importe_total >= 0)
);

create table if not exists public.comunicaciones (
  id bigint generated by default as identity primary key,
  -- El respaldo MySQL no declaraba CLI_ID como único; conservamos el vínculo lógico.
  cliente_id bigint not null,
  tipo text not null check (tipo in ('email')),
  asunto text not null,
  mensaje text not null,
  enviado_en timestamptz not null default now(),
  enviado_por text not null
);

-- Estas tablas se consultan exclusivamente desde Route Handlers con service_role.
-- Ningún navegador debe poder leer datos operativos directamente por PostgREST.
alter table public.inventario enable row level security;
alter table public.ventas enable row level security;
alter table public.venta_items enable row level security;
alter table public.comunicaciones enable row level security;

create or replace function public.registrar_venta(
  p_items jsonb,
  p_veterinario_nombre text,
  p_notas text default ''
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  item jsonb;
  producto public.inventario%rowtype;
  nueva_venta_id bigint;
  total numeric(12,2) := 0;
  unidades integer := 0;
  cantidad integer;
begin
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'La venta debe incluir al menos un producto';
  end if;

  for item in select * from jsonb_array_elements(p_items)
  loop
    cantidad := (item ->> 'cantidad')::integer;
    if cantidad is null or cantidad <= 0 then raise exception 'Cantidad inválida'; end if;

    select * into producto from public.inventario
    where id = (item ->> 'producto_id')::bigint for update;
    if not found then raise exception 'Producto no encontrado'; end if;
    if producto.stock < cantidad then
      raise exception 'Stock insuficiente para %', producto.nombre;
    end if;
    total := total + producto.precio * cantidad;
    unidades := unidades + cantidad;
  end loop;

  insert into public.ventas (veterinario_nombre, importe_total, cantidad_items, notas)
  values (p_veterinario_nombre, total, unidades, nullif(trim(p_notas), ''))
  returning id into nueva_venta_id;

  for item in select * from jsonb_array_elements(p_items)
  loop
    cantidad := (item ->> 'cantidad')::integer;
    select * into producto from public.inventario
    where id = (item ->> 'producto_id')::bigint for update;
    insert into public.venta_items (venta_id, producto_id, producto_nombre, cantidad, precio_unitario, importe_total)
    values (nueva_venta_id, producto.id, producto.nombre, cantidad, producto.precio, producto.precio * cantidad);
    update public.inventario set stock = stock - cantidad, actualizado_en = now() where id = producto.id;
  end loop;

  return jsonb_build_object('id', nueva_venta_id, 'importe_total', total, 'cantidad_items', unidades);
end;
$$;

revoke all on function public.registrar_venta(jsonb, text, text) from public;
grant execute on function public.registrar_venta(jsonb, text, text) to service_role;
