create table if not exists public.turnos (
  id bigint generated by default as identity primary key,
  fecha date not null,
  hora time not null,
  cliente_id bigint not null,
  paciente_id bigint not null,
  motivo text not null,
  estado text not null default 'pendiente' check (estado in ('pendiente','confirmado','atendido','cancelado')),
  notas text,
  creado_por text not null,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);
create index if not exists turnos_fecha_idx on public.turnos(fecha, hora);
create table if not exists public.consultas_nuevas (
  id bigint generated by default as identity primary key,
  paciente_id bigint not null,
  fecha date not null default current_date,
  titulo text not null,
  peso numeric(8,2),
  temperatura numeric(5,2),
  detalle text not null,
  tratamiento text,
  profesional text,
  creado_por text not null,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);
create index if not exists consultas_nuevas_paciente_idx on public.consultas_nuevas(paciente_id, fecha desc);
alter table public.turnos enable row level security;
alter table public.consultas_nuevas enable row level security;
