"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

type Client = Record<string, string | number | null | undefined>;
const value = (item: unknown) => String(item ?? "").trim();

export function ClientActions({ cliente }: { cliente: Client }) {
  const router = useRouter(); const [error, setError] = useState("");
  const rawPhone = value(cliente.cli_celu) || value(cliente.cli_tel1); const phone = rawPhone.replace(/\D/g, ""); const whatsapp = phone.replace(/^0/, "").replace(/^15/, ""); const email = value(cliente.cli_mail);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); const response = await fetch(`/api/clientes/${cliente.cli_id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(Object.fromEntries(new FormData(event.currentTarget))) }); if (!response.ok) return setError((await response.json()).error ?? "No se pudo guardar"); router.refresh(); }
  return <div className="mb-4 flex flex-wrap gap-2">{phone && <a href={`tel:${phone}`} className="rounded-lg border bg-white px-3 py-2 text-sm font-medium text-slate-700">📞 Llamar</a>}{whatsapp && <a href={`https://wa.me/${whatsapp.startsWith("54") ? whatsapp : `54${whatsapp}`}`} target="_blank" rel="noreferrer" className="rounded-lg bg-emerald-600 px-3 py-2 text-sm font-medium text-white">WhatsApp</a>}{email && email !== "0" && <a href={`mailto:${email}`} className="rounded-lg border bg-white px-3 py-2 text-sm font-medium text-slate-700">✉️ Email</a>}<details className="rounded-lg border bg-white p-2"><summary className="cursor-pointer text-sm font-medium text-slate-700">✏️ Editar cliente</summary><form onSubmit={submit} className="mt-3 grid gap-2 sm:grid-cols-2"><Input name="cli_nombre" defaultValue={value(cliente.cli_nombre)} placeholder="Nombre"/><Input name="cli_apellido" defaultValue={value(cliente.cli_apellido)} placeholder="Apellido"/><Input name="cli_celu" defaultValue={value(cliente.cli_celu)} placeholder="Celular"/><Input name="cli_tel1" defaultValue={value(cliente.cli_tel1)} placeholder="Teléfono"/><Input name="cli_mail" defaultValue={value(cliente.cli_mail)} placeholder="Email"/><Input name="cli_cuit" defaultValue={value(cliente.cli_cuit)} placeholder="CUIT"/><Input name="cli_domic" defaultValue={value(cliente.cli_domic)} placeholder="Domicilio"/><Input name="cli_entre" defaultValue={value(cliente.cli_entre)} placeholder="Entre calles"/><Input name="cli_loc" defaultValue={value(cliente.cli_loc)} placeholder="Localidad"/><Input name="cli_cp" defaultValue={value(cliente.cli_cp)} placeholder="Código postal"/><Input name="cli_prov" defaultValue={value(cliente.cli_prov)} placeholder="Provincia"/><Input name="cli_pais" defaultValue={value(cliente.cli_pais)} placeholder="País"/><Input name="cli_razsoc" defaultValue={value(cliente.cli_razsoc)} placeholder="Razón social"/><Input name="cli_repiva" defaultValue={value(cliente.cli_repiva)} placeholder="Condición IVA"/><Input name="cli_tipo" defaultValue={value(cliente.cli_tipo)} placeholder="Tipo"/><Button type="submit">Guardar cambios</Button></form>{error && <p className="mt-2 text-sm text-red-600">{error}</p>}</details></div>;
}
