import Link from "next/link";
import { createAdminClient } from "@/lib/supabase/admin";
import { argentinaDate } from "@/lib/date";
import { getSession } from "@/lib/auth";

const today = () => argentinaDate();
const clean = (value: unknown) => String(value ?? "").trim() || "—";

export default async function DashboardPage() {
  const session = await getSession(); const supabase = createAdminClient(); const now = today();
  const [{ count: clientes },{ count: pacientes },{ count: vacunas },{ count: hc },{ count: ecografias },{ data: turnos },{ data: inventario },{ data: consultas },{ data: proximasVacunas }] = await Promise.all([
    supabase.from("clientes").select("*", { count:"exact", head:true }), supabase.from("pacientes").select("*", { count:"exact", head:true }), supabase.from("vacunas").select("*", { count:"exact", head:true }), supabase.from("hccab").select("*", { count:"exact", head:true }), supabase.from("ecografias").select("*", { count:"exact", head:true }),
    supabase.from("turnos").select("*").gte("fecha",now).neq("estado","cancelado").order("fecha").order("hora").limit(8),
    supabase.from("inventario").select("id,nombre,stock,stock_minimo").limit(200),
    supabase.from("consultas_nuevas").select("id,paciente_id,fecha,titulo,profesional").order("fecha",{ascending:false}).limit(6),
    supabase.from("vacunas").select("vac_id,vac_idpaciente,vac_fproxima,vac_fproxima_seg,vac_marca,vac_clase").not("vac_fproxima_seg", "is", null).neq("vac_fproxima_seg", "").order("vac_fproxima_seg", { ascending: true }).limit(8),
  ]);
  const low = (inventario ?? []).filter(item => Number(item.stock) <= Number(item.stock_minimo));
  const patientIds = [...new Set([...(turnos ?? []).map(t=>Number(t.paciente_id)), ...(consultas ?? []).map(c=>Number(c.paciente_id)), ...(proximasVacunas ?? []).map(v=>Number(v.vac_idpaciente))])];
  const { data: pets } = patientIds.length ? await supabase.from("pacientes").select("pac_id,pac_nombre").in("pac_id",patientIds) : {data:[]};
  const petName=(id:number)=>clean(pets?.find(p=>Number(p.pac_id)===id)?.pac_nombre);
  const stats=[{label:"Clientes",value:clientes,icon:"👥",href:"/dashboard/clientes"},{label:"Pacientes",value:pacientes,icon:"🐾",href:"/dashboard/pacientes"},{label:"Vacunas",value:vacunas,icon:"💉",href:"/dashboard/vacunas"},{label:"Historias clínicas",value:hc,icon:"📋",href:"/dashboard/historia-clinica"},{label:"Ecografías",value:ecografias,icon:"🔬",href:"/dashboard/ecografias"}];
  const vaccineStatus=(vacuna:{vac_fproxima_seg?:string|null})=>String(vacuna.vac_fproxima_seg??"")<now?"text-red-700":"text-amber-700";
  return <div><h1 className="mb-1 text-2xl font-semibold text-slate-800">Bienvenido, {session?.nombre}</h1><p className="mb-6 text-sm text-slate-500">Resumen operativo · {now}</p><div className="grid grid-cols-2 gap-3 md:grid-cols-3 lg:grid-cols-5">{stats.map(s=><Link key={s.label} href={s.href} className="rounded-xl border bg-white px-4 py-5 shadow-sm transition hover:border-slate-400 hover:shadow"><div className="text-2xl">{s.icon}</div><div className="text-2xl font-bold text-slate-800">{s.value?.toLocaleString("es-AR")}</div><div className="text-xs text-slate-500">{s.label}</div></Link>)}</div><div className="mt-6 grid gap-5 lg:grid-cols-2"><Panel title="🗓️ Próximos turnos" href="/dashboard/turnos">{turnos?.length ? turnos.map(t=><Link key={t.id} href={`/dashboard/pacientes/${t.paciente_id}`} className="flex items-center justify-between gap-3 border-b py-3 last:border-0"><span className="font-medium text-slate-800">{t.fecha} · {String(t.hora).slice(0,5)}</span><span className="text-sm text-slate-600">{petName(Number(t.paciente_id))} · {t.motivo}</span><span className="text-xs text-slate-500">{t.estado}</span></Link>) : <Empty text="No hay turnos próximos."/>}</Panel><Panel title="💉 Próximas vacunas" href="/dashboard/vacunas">{proximasVacunas?.length ? proximasVacunas.map(v=><Link key={v.vac_id} href={`/dashboard/pacientes/${v.vac_idpaciente}`} className="flex items-center justify-between gap-3 border-b py-3 last:border-0"><span className="text-sm font-medium text-slate-800">{petName(Number(v.vac_idpaciente))}</span><span className="text-sm text-slate-600">{clean(v.vac_marca)} · {clean(v.vac_clase)}</span><span className={`text-xs ${vaccineStatus(v)}`}>{clean(v.vac_fproxima)}</span></Link>) : <Empty text="No hay próximas vacunas registradas."/>}</Panel><Panel title={`📦 Stock bajo (${low.length})`} href="/dashboard/inventario">{low.length ? low.slice(0,8).map(p=><div key={p.id} className="flex justify-between border-b py-3 text-sm last:border-0"><span className="font-medium text-slate-800">{p.nombre}</span><span className="text-amber-700">{p.stock} / mín. {p.stock_minimo}</span></div>) : <Empty text="El stock está por encima del mínimo."/>}</Panel><Panel title="🩺 Últimas consultas" href="/dashboard/historia-clinica">{consultas?.length ? consultas.map(c=><Link key={c.id} href={`/dashboard/pacientes/${c.paciente_id}`} className="flex justify-between gap-3 border-b py-3 last:border-0"><span className="text-sm font-medium text-slate-800">{petName(Number(c.paciente_id))}</span><span className="flex-1 text-right text-sm text-slate-600">{c.titulo}</span><span className="text-xs text-slate-500">{c.fecha}</span></Link>) : <Empty text="Todavía no hay consultas nuevas."/>}</Panel></div></div>;
}
function Panel({title,href,children}:{title:string;href:string;children:React.ReactNode}){return <section className="rounded-xl border bg-white p-4 shadow-sm"><div className="mb-2 flex items-center justify-between"><h2 className="font-semibold text-slate-800">{title}</h2><Link href={href} className="text-xs text-blue-700 hover:underline">Ver todo</Link></div>{children}</section>}
function Empty({text}:{text:string}){return <p className="py-4 text-sm text-slate-400">{text}</p>}
